server:
  port: 9093

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: com.ybtccc.gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: 163
        uri: http://www.163.com
        predicates:
        - Path=/163

